### Array and List 

In [1]:
print("Array Tutorial")

Array Tutorial


In [2]:
# Sets
set_var=set()
print(set_var)

set()


In [3]:
type(set_var)

set

In [4]:
value=[1,2,3,4,5]

In [5]:
print(value)

[1, 2, 3, 4, 5]


In [6]:
value.append("Sandeep")

In [7]:
value

[1, 2, 3, 4, 5, 'Sandeep']

In [8]:
value1=[1,2,3,4,5,6,7,8]

In [9]:
# dictionary
dic={1,2,3}
type(dic)

set

In [10]:
dic2={1:"Sandeep"}
type(dic2)

dict

In [11]:
# tuple
my_tuple=tuple()

In [12]:
type(my_tuple)

tuple

In [13]:
my_tuple=("Sandeep","Kumar","Pranav")

In [14]:
my_tuple

('Sandeep', 'Kumar', 'Pranav')

In [15]:
# Numpy
import numpy as np

In [16]:
my_list=[1,2,3,4,5,6]

In [17]:
arr=np.array(my_list)

In [18]:
arr

array([1, 2, 3, 4, 5, 6])

In [19]:
type(arr)

numpy.ndarray

In [20]:
print(arr)

[1 2 3 4 5 6]


In [21]:
arr.shape

(6,)

In [22]:
my_list1=[1,2,3,4,5,6]
my_list2=[2,3,4,5,6,7]
my_list3=[3,4,5,6,7,8]

arr=np.array([my_list1,my_list2,my_list3])

In [23]:
arr

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7, 8]])

In [24]:
print(arr)

[[1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]]


In [25]:
arr.shape

(3, 6)

In [26]:
arr.reshape(2,9)

array([[1, 2, 3, 4, 5, 6, 2, 3, 4],
       [5, 6, 7, 3, 4, 5, 6, 7, 8]])

In [27]:
arr2=arr.reshape(6,3)

In [28]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]
 [3 4 5]
 [6 7 8]]


In [29]:
arr.shape

(3, 6)

In [30]:
arr2.shape

(6, 3)

In [31]:
my_list=[1,2,3,4,5,6]

In [32]:
arr3=np.array(my_list)

In [33]:
arr3

array([1, 2, 3, 4, 5, 6])

In [34]:
arr3[4]

5

In [35]:
arr2[1][1]

5

In [36]:
my_lst1=[1,2,3,4,5,6]
my_lst2=[2,3,4,5,6,7]
my_lst3=[3,4,5,6,7,8]

ar=np.array([my_lst1,my_lst2,my_lst3])

In [37]:
print(ar)

[[1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]]


In [38]:
arr[2][3]

6

In [39]:
arr[0:1,:]

array([[1, 2, 3, 4, 5, 6]])

In [40]:
arr[0:1,0:1]

array([[1]])

In [41]:
arr[1:,3:5]

array([[5, 6],
       [6, 7]])

In [42]:
arr[1:,2:4]

array([[4, 5],
       [5, 6]])

In [43]:
arr0=np.arange(1,10)

In [44]:
arr0

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr0=np.arange(0,20,step=3)

In [46]:
arr0

array([ 0,  3,  6,  9, 12, 15, 18])

In [47]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [48]:
#broadcasting
arr0[3:]=100

In [49]:
arr0

array([  0,   3,   6, 100, 100, 100, 100])

In [50]:
arr0[3:]=500

In [51]:
arr0

array([  0,   3,   6, 500, 500, 500, 500])

In [52]:
ar1=arr0.copy()

In [53]:
ar1

array([  0,   3,   6, 500, 500, 500, 500])

In [54]:
print(arr0)
ar1[2:]=5
print(ar1)

[  0   3   6 500 500 500 500]
[0 3 5 5 5 5 5]


In [55]:
ar1

array([0, 3, 5, 5, 5, 5, 5])

In [56]:
arr0

array([  0,   3,   6, 500, 500, 500, 500])

In [57]:

arr0<2

array([ True, False, False, False, False, False, False])

In [58]:
arr[arr<2]

array([1])

In [59]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
np.ones(3)

array([1., 1., 1.])

In [61]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [62]:
np.random.rand(3,3)

array([[0.67534716, 0.56016012, 0.2658888 ],
       [0.69154899, 0.81016241, 0.83808644],
       [0.70387347, 0.78306412, 0.4593221 ]])

In [63]:
arrr=np.random.randn(3,3)

In [64]:
arrr

array([[-0.15979619,  0.19159054,  0.89257548],
       [ 1.94182828,  2.11298515, -0.02288058],
       [-1.33774219,  1.42050657,  0.98107858]])

In [65]:
np.random.randint(0,100,9)

array([67, 74, 66, 49, 92, 49, 17, 40, 45])

In [66]:
np.random.randint(0,100,9).reshape(3,3)

array([[82,  2,  1],
       [30, 45, 45],
       [86, 92, 12]])

In [67]:
np.random.random_sample((1,5))

array([[0.63340355, 0.50891484, 0.41869772, 0.35423321, 0.29367974]])

In [ ]:
### Hope you enjoyed the Tutorial

### ~